name: Tag & Release

on:
  workflow_dispatch:

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write # to push packages to GitHub

jobs:
  release:
    name: Release ${{ github.event.inputs.TAG_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: Greenroom-Robotics/workflow-telemetry-action@main

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Login to npm github packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com
          scope: '@greenroom-robotics'
          token: ${{ github.token }}
        env:
          API_TOKEN_GITHUB: ${{ github.token }}

      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile
        env:
          API_TOKEN_GITHUB: ${{ github.token }}

      - name: Test
        run: pnpm run test

      - name: Release
        id: release
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: pnpm run --stream release
